name: Build and Release APK
on: [push, workflow_dispatch]

permissions: write-all

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Debug Git Info
        run: |
          echo "Current branch:"
          git branch --show-current
          echo "All branches:"
          git branch -a
          echo "Git status:"
          git status

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'

      - name: Flutter pub get
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Debug Build Output
        run: |
          echo "APK build location:"
          find . -name "*.apk"
          echo "Build directory contents:"
          ls -R build/

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: build/app/outputs/flutter-apk/app-release.apk
          tag_name: build-${{ github.run_number }}
          name: "Build ${{ github.run_number }}"
          body: |
            Automated build from GitHub Actions
            Branch: ${{ github.ref_name }}
            Commit: ${{ github.sha }}
            
            Download app-release.apk to install on your Android device.
          draft: false
          prerelease: false
          fail_on_unmatched_files: true
