name: Build and Release APK
on: [push, workflow_dispatch]

permissions: write-all

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.9'
          channel: 'stable'

      - name: Show Flutter version
        run: flutter --version

      - name: Flutter doctor
        run: flutter doctor -v

      - name: Flutter clean
        run: flutter clean

      - name: Flutter pub get
        run: flutter pub get

      - name: Build APK
        run: |
          flutter build apk --release --verbose
          echo "APK build completed"
          ls -l build/app/outputs/flutter-apk/

      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: build/app/outputs/flutter-apk/app-release.apk
          tag_name: build-${{ github.run_number }}
          name: "Build ${{ github.run_number }}"
          body: |
            Automated build from GitHub Actions
            Download app-release.apk to install on your Android device.
            
            Build details:
            - Run number: ${{ github.run_number }}
            - Commit: ${{ github.sha }}
            - Branch: ${{ github.ref_name }}
          draft: false
          prerelease: false
          fail_on_unmatched_files: true
