name: Build and Release APK
on: push

permissions: write-all

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'

      - name: Flutter pub get
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Debug APK Location
        run: |
          echo "Looking for APK files..."
          find . -name "*.apk"
          echo "Contents of build/app/outputs/flutter-apk/:"
          ls -la build/app/outputs/flutter-apk/

      - name: Rename APK
        run: |
          mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/nixie_clock.apk
          echo "APK renamed to nixie_clock.apk"
          ls -la build/app/outputs/flutter-apk/

      - name: Release APK
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/nixie_clock.apk"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: "v1.0.${{ github.run_number }}"
          name: "Release v1.0.${{ github.run_number }}"
          body: "Download nixie_clock.apk to install on your Android device"
          allowUpdates: true
          removeArtifacts: false
          artifactErrorsFailBuild: true
