name: Build and Release APK
on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

permissions: write-all

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'

      - name: Show current directory and branch
        run: |
          pwd
          git branch --show-current
          git status

      - name: Flutter pub get
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Debug APK Location
        run: |
          echo "Looking for APK files..."
          find . -name "*.apk"
          echo "Contents of build/app/outputs/flutter-apk/:"
          ls -la build/app/outputs/flutter-apk/

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/app/outputs/flutter-apk/app-release.apk
          tag_name: release-${{ github.run_number }}
          name: "Release ${{ github.run_number }}"
          body: "Download app-release.apk to install on your Android device"
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_unmatched_files: true
